### PR TITLE
Password generation cleanup, add mooltipass info

### PR DESCRIPTION
**Pull request by mremallin**
- Cleaned up password generation and moved to own function
- Added length validation of supplied username and password
- Minor formatting cleanup

### CODE REVIEW

**Comment by oSquat** [comment]
Great, looks good - especially the version function I'd been putting off. I've got time today and will do some of my own tweaking and cleaning up; update the readme, tag and push the new version to PyPI. 

Thanks again for contributing!

**Comment by mremallin** [comment]
No problem! Figure I may as well contribute to an existing project than try and spin another (unsuccessful) one.

I think the next thing I'll start looking at is either delete or favourites. It's getting annoying spinning through my passwords to log in to github... XD

**Comment by oSquat** [comment]
Favorites would be great. I would suggest a whole utility under mooltipy called mpfavorite (e.g. mooltipy favorite  {get|set|del} ... ). If you want to take that area on I'll avoid it myself. The only conflict we may encounter is the way to spell "favorite vs favourite" :^)

Deleting would be OK too, but it appears to be quite an undertaking according to Limpkin the creator who has avoided outlining the process for deleting contexts. I think it requires going into management mode and manipulating data at a pretty low level.

Just an FYI I'll update the readme with my contact if you want to collaborate in IRC or through e-mail.

**Comment by mremallin** [comment]
Cool. I guess I can drop the 'u' for now :P 

I'll avoid delete for now, as I'm using mooltipass_comms.py for inspiration. I've started on listing the available nodes/children and it already lots of fun... XD I'll move my code over to mpfavorites.py once it's working.

Thanks, I'll probably pop on IRC later once I fix my bouncer.

**Pull request merged**
